version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run: python -m pip install .[dev]
      - run: python setup.py test --addopts -v
      - run: cd docs && make doctest
